import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import path from "path";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // EcoFlowJSDocs: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  EcoFlowJSDevDocs: [
    // {
    //   type: "autogenerated",
    //   dirName: "dev-docs",
    // },
    {
      type: "doc",
      id: "dev-docs/getting-started",
      label: "Getting Started",
      customProps: {
        icon: "entypo:rocket",
      },
    },
    {
      type: "doc",
      id: "dev-docs/cli",
      label: "Command-line Usage",
      customProps: {
        icon: "clarity:terminal-solid",
      },
    },
    {
      type: "doc",
      id: "dev-docs/upgrade",
      label: "Upgrading EcoFlowJS",
      customProps: {
        icon: "eos-icons:package-upgrade",
      },
    },
    {
      type: "doc",
      id: "dev-docs/cloning",
      label: "Clone Project",
      customProps: {
        icon: "fluent-mdl2:clone-to-desktop",
      },
    },
    {
      type: "category",
      label: "API Reference",
      description: "API Reference",
      customProps: {
        icon: "icon-park-outline:api",
      },
      link: {
        type: "generated-index",
        description: "API Reference",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "dev-docs/api-docs",
        },
      ],
    },
    {
      type: "category",
      label: "Creating Nodes",
      customProps: {
        icon: "gravity-ui:nodes-left",
      },
      link: {
        type: "doc",
        id: "dev-docs/creating-nodes/creating-nodes",
      },
      items: [
        "dev-docs/creating-nodes/creating-your-first-node",
        "dev-docs/creating-nodes/node-manifest",
        "dev-docs/creating-nodes/input-types",
        "dev-docs/creating-nodes/controllers",
        "dev-docs/creating-nodes/Packaging",
      ],
    },
    {
      type: "category",
      label: "Contributing",
      customProps: {
        icon: "mynaui:user-octagon",
      },
      link: {
        type: "doc",
        id: "dev-docs/contributing/contributing",
      },
      items: ["dev-docs/contributing/guide"],
    },
    {
      type: "doc",
      id: "dev-docs/support",
      label: "Support",
      customProps: {
        icon: "mdi:support",
      },
    },
    {
      type: "doc",
      id: "dev-docs/Feedback",
      label: "Feedback",
      customProps: {
        icon: "codicon:feedback",
      },
    },
    {
      type: "doc",
      id: "dev-docs/SECURITY",
      label: "Security Policy",
      customProps: {
        icon: "material-symbols:security-rounded",
      },
    },
    {
      type: "doc",
      id: "dev-docs/License",
      label: "License",
      customProps: {
        icon: "tabler:license",
      },
    },
    {
      type: "doc",
      id: "dev-docs/authors",
      label: "Authors",
      customProps: {
        icon: "oui:user",
      },
    },
  ],
  EcoFlowJSUserDocs: [
    {
      type: "autogenerated",
      dirName: "user-docs",
    },
  ],
};

export default sidebars;
